name: Weekly SEO Metrics Sync to Airtable

on:
  schedule:
    - cron: "0 20 * * 1"  # Runs every Monday at 8PM UTC
  workflow_dispatch:     # Allows manual run from the GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run SEO Airtable sync
      env:
        AIRTABLE_PAT: ${{ secrets.AIRTABLE_PAT }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
      run: python seo_airtable.py
